context:
  name: pygyat
  version: "1.0.8"
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 3537ebac3021bd7f9c959d7b2ad94a65b868f6c37d2bb19faf2255c44f181184

build:
  script: python -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    # pygyat contains unix-style scripts that are not supported on Windows
    - __unix

tests:
  - python:
      imports:
        - pygyat
      pip_check: true
      python_version: ${{ python_min }}
  - script:
      content: |
        pygyat --version
        gyat2py --version
        py2gyat --version

about:
  homepage: https://pygyat.vercel.app
  summary: Python with rizz.
  description: |
    Be a sigma with PyGyat - a Python preprocessor that translates Python into brainrot
  license: MIT
  license_file: LICENSE
  repository: https://github.com/shamith09/pygyat

extra:
  recipe-maintainers:
    - pavelzw
